### ISSUE TITLE
1.1.4版本的依赖directattribute没有1.0.5版本哦

### ISSUE THREAD

**Issue by MeeplePlanet** [labbbirder/UnityInjection#1]
$ openupm add com.bbbirder.injection
WARN 404 package com.bbbirder.directattribute@1.0.5 is not a valid choice of 1.0.4, 1.0.1, 1.0.0, 0.0.20, 0.0.18, 0.0.17, 0.0.16, 0.0.13, 0.0.12, 0.0.9, 0.0.8, 0.0.6
notice suggest to install com.bbbirder.directattribute@1.0.5 or a replaceable version manually
ERR! missing dependencies please resolve thie issue or run with option -f to ignore the warning

**Comment by labbbirder** [comment]
@Anomalybound  感谢issue，directretrieveattribute已经提了版本。ci通过后应该就可以install了
