### ISSUE TITLE
能否提供完整的demo？

### ISSUE THREAD

**Issue by Miucann** [labbbirder/UnityInjection#2]
发现同时导入此工程和依赖工程的时候，sample无法正常运行。同时貌似缺少monoceil的库

**Comment by labbbirder** [comment]
你好， @Miucann ，如你所说，Sample工程是旧了。更新到1.3.21版本应该能解决问题。

如果更新后还是出现问题。请按以下步骤排查问题：

step1. 请先检查Windows/PackageManager内是否有下载失败的package（红色感叹号图标）

step2. 如果上一步无误，是否方便提供以下信息：

  - Unity版本
  - UnityInjection版本
  - Packages/manifest.json内容

**Comment by Miucann** [comment]
> 你好， @Miucann ，如你所说，Sample工程是旧了。更新到1.3.21版本应该能解决问题。
> 
> 如果更新后还是出现问题。请按以下步骤排查问题：
> 
> step1. 请先检查Windows/PackageManager内是否有下载失败的package（红色感叹号图标）
> 
> step2. 如果上一步无误，是否方便提供以下信息：
> 
> * Unity版本
> * UnityInjection版本
> * Packages/manifest.json内容

感谢，使用最新的版本后已经成功的调通了demo
