### ISSUE TITLE
Unity2023 is not supported

### ISSUE THREAD

**Issue by xzaxzaazx** [labbbirder/UnityInjection#5]
Can not inject in editor, Not sure why, maybe the API changed.
Unity2022 is tried, No problem.

**Comment by labbbirder** [comment]
Thx, I'll check it later.

**Comment by labbbirder** [comment]
Hi bro, UnityInjectionV2 could be the fix

**Comment by LiuLeipengsc** [comment]
It seems that UnityInjectionV2 does not support Android IL2CPP builds.

**Comment by LiuLeipengsc** [comment]
> Hi bro, UnityInjectionV2 could be the fix

It seems that UnityInjectionV2 does not support Android IL2CPP builds.

**Comment by labbbirder** [comment]
@LiuLeipengsc I tested on my pc, every thing works well. Please check your console if there is an error.
